Repository GSG-FC02/Urban-Natural-5, pull requests merged in 2021-03, with the labels that each got.

#4 File structure
  css/style.css
  html/book.html
  html/calender.html
  html/info.html
  html/landing2.html
  html/questions.html
  html/successful.html
  img/calender.png
  img/logo.png
  index.html
Labels: Done

#12 create the calender Page and make the style
  css/style.css
  html/calender.html
Labels: awaiting-review

#14 Build the contact info page and style it
  css/style.css
  html/info.html
Labels: awaiting-review

#15 Landing page
  css/style.css
  html/info.html
  index.html
Labels: awaiting-review

#13 6 landing page2
  css/style.css
  html/landing2.html
Labels: awaiting-review

#17 add book page
  css/style.css
  html/book.html
Labels: awaiting-review

#21 creat successful page
  css/style.css
  html/successful.html
  img/Like.png
Labels: awaiting-review

#20 edit some details in whole app
  css/style.css
  html/book.html
  html/questions.html
Labels: in-progress

#18 write the read me
  README.md
Labels: awaiting-review
